config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
end

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains 
      = pluralize(object.errors.count, 'error')

    ul
      - object.errors.full_messages.each do |msg|
        li
          | *
          = msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol.microposts
    = render partial: 'shared/feed_item', collection: @feed_items
  = will_paginate @feed_items

app/views/shared/_feed_item.html.slim
li id=feed_item.id
  = link_to gravatar_for(feed_item.user), feed_item.user
  span.user
    = link_to feed_item.user.name, feed_item.user
  = render partial: 'shared/micropost', locals: { micropost: feed_item }

app/views/shared/_homepage.html.slim
.center.hero-unit
  h1 Welcome to the Sample App
  h2
    This is the home page for the 
    a href = 'http://railstutorial.jp'
      | Ruby on Rails Tutorial
    |  sample application.

  = link_to 'Sign up now!', signup_path, { class: ['btn', 'btn-large', 'btn-primary'] }
= link_to image_tag('rails.png', alt: 'Rails'), 'http://rubyonrails.org/'

app/views/shared/_micropost.html.slim
span.content = wrap(micropost.content)
span.timestamp
  = "Posted#{time_ago_in_words(micropost.created_at)} ago."
- if current_user?(micropost.user)
  = link_to 'delete', micropost, method: :delete,
    data: { confirm: 'Your sure?' },
    title: micropost.content

app/views/shared/_micropost_form.html.slim
= form_for(@micropost) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: 'Compose new micropost...'
    = f.submit 'Post', class: 'btn btn-large btn-primary'

app/views/shared/_stats.html.slim
- @user ||= current_user
.stats
  = link_to "#{following_user_path(@user)}" do
    strong#following.stat
      = @user.followed_users.count
    |  following
  = link_to "#{followers_user_path(@user)}" do
    strong#followers.stat
      = @user.followers.count
    |  followers

app/views/shared/_user_homepage.html.slim
.row
  aside.span4
    section
      = render 'shared/user_info'
    section
      = render 'shared/stats'
    section
      = render 'shared/micropost_form'
  .span8
    h3 Micropost Feed
    = render 'shared/feed'

app/views/shared/_user_info.html.slim
= link_to user_path(current_user) do
  = gravatar_for current_user, size: 52
h1
  = current_user.name
span
  = link_to 'view my profile', current_user
span
  = pluralize(current_user.microposts.count, 'micropost')