config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    a href="http://railstutorial.jp/"
      | Rails Tutorial
    |  by Michael Hartl
  nav
    ul
      li = link_to 'About', about_path
      li = link_to 'Contact', contact_path
      li
        a href="http://news.railstutorial.jp/"
          | News

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to 'sample app', root_path, { id: 'logo' }
      nav
        ul.nav.pull-right
          li = link_to 'Home', root_path
          li = link_to 'Help', help_path
          - if signed_in?
            li = link_to 'Users', users_path
            li#fat-menu.dropdown
              = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
                | Account
                b.caret
              ul.dropdown-menu
                li = link_to 'Profile', current_user
                li = link_to 'Settings', edit_user_path(current_user)
                li.divider
                li = link_to 'Sign out', signout_path, method: 'delete'
          - else
            li = link_to 'Sign in', signin_path

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?